config/routes.rb
Rails.application.routes.draw do
  resources :payements
  resources :teaches
  resources :instructors
  resources :takes
  resources :courses
  resources :st_has_deps
  resources :departments
  resources :students
  resources :studnts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  belongs_to :department
end

app/models/payement.rb
class Payement < ApplicationRecord
  belongs_to :student
end

app/models/st_has_dep.rb
class StHasDep < ApplicationRecord
  belongs_to :department
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/studnt.rb
class Studnt < ApplicationRecord
end

app/models/take.rb
class Take < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/teache.rb
class Teache < ApplicationRecord
  belongs_to :instructor
  belongs_to :course
end

app/controllers/takes_controller.rb
class TakesController < ApplicationController
  before_action :set_take, only: [:show, :edit, :update, :destroy]

  # GET /takes
  # GET /takes.json
  def index
    @takes = Take.all
  end

  # GET /takes/1
  # GET /takes/1.json
  def show
  end

  # GET /takes/new
  def new
    @take = Take.new
  end

  # GET /takes/1/edit
  def edit
  end

  # POST /takes
  # POST /takes.json
  def create
    @take = Take.new(take_params)

    respond_to do |format|
      if @take.save
        format.html { redirect_to @take, notice: 'Take was successfully created.' }
        format.json { render :show, status: :created, location: @take }
      else
        format.html { render :new }
        format.json { render json: @take.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /takes/1
  # PATCH/PUT /takes/1.json
  def update
    respond_to do |format|
      if @take.update(take_params)
        format.html { redirect_to @take, notice: 'Take was successfully updated.' }
        format.json { render :show, status: :ok, location: @take }
      else
        format.html { render :edit }
        format.json { render json: @take.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /takes/1
  # DELETE /takes/1.json
  def destroy
    @take.destroy
    respond_to do |format|
      format.html { redirect_to takes_url, notice: 'Take was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_take
      @take = Take.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def take_params
      params.require(:take).permit(:student_id, :course_id)
    end
end

app/controllers/teaches_controller.rb
class TeachesController < ApplicationController
  before_action :set_teach, only: [:show, :edit, :update, :destroy]

  # GET /teaches
  # GET /teaches.json
  def index
    @teaches = Teache.all
  end

  # GET /teaches/1
  # GET /teaches/1.json
  def show
  end

  # GET /teaches/new
  def new
    @teach = Teache.new
  end

  # GET /teaches/1/edit
  def edit
  end

  # POST /teaches
  # POST /teaches.json
  def create
    @teach = Teache.new(teach_params)

    respond_to do |format|
      if @teach.save
        format.html { redirect_to @teach, notice: 'Teache was successfully created.' }
        format.json { render :show, status: :created, location: @teach }
      else
        format.html { render :new }
        format.json { render json: @teach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teaches/1
  # PATCH/PUT /teaches/1.json
  def update
    respond_to do |format|
      if @teach.update(teach_params)
        format.html { redirect_to @teach, notice: 'Teache was successfully updated.' }
        format.json { render :show, status: :ok, location: @teach }
      else
        format.html { render :edit }
        format.json { render json: @teach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teaches/1
  # DELETE /teaches/1.json
  def destroy
    @teach.destroy
    respond_to do |format|
      format.html { redirect_to teaches_url, notice: 'Teache was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teach
      @teach = Teache.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teach_params
      params.require(:teach).permit(:instructor_id, :course_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/payements_helper.rb
module PayementsHelper
end

app/helpers/st_has_deps_helper.rb
module StHasDepsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/studnts_helper.rb
module StudntsHelper
end

app/helpers/takes_helper.rb
module TakesHelper
end

app/helpers/teaches_helper.rb
module TeachesHelper
end

app/views/teaches/_form.html.erb
<%= form_for(teach) do |f| %>
  <% if teach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teach.errors.count, "error") %> prohibited this teach from being saved:</h2>

      <ul>
      <% teach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :instructor_id %>
    <%= f.text_field :instructor_id %>
  </div>

  <div class="field">
    <%= f.label :course_id %>
    <%= f.text_field :course_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teaches/edit.html.erb
<h1>Editing Teach</h1>

<%= render 'form', teach: @teach %>

<%= link_to 'Show', @teach %> |
<%= link_to 'Back', teaches_path %>

app/views/teaches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teaches</h1>

<table>
  <thead>
    <tr>
      <th>Instructor</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teaches.each do |teach| %>
      <tr>
        <td><%= teach.instructor %></td>
        <td><%= teach.course %></td>
        <td><%= link_to 'Show', teach %></td>
        <td><%= link_to 'Edit', edit_teach_path(teach) %></td>
        <td><%= link_to 'Destroy', teach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teach', new_teach_path %>

app/views/teaches/new.html.erb
<h1>New Teach</h1>

<%= render 'form', teach: @teach %>

<%= link_to 'Back', teaches_path %>

app/views/teaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Instructor:</strong>
  <%= @teach.instructor %>
</p>

<p>
  <strong>Course:</strong>
  <%= @teach.course %>
</p>

<%= link_to 'Edit', edit_teach_path(@teach) %> |
<%= link_to 'Back', teaches_path %>