config/routes.rb
Rails.application.routes.draw do
  resources :payements
  resources :teaches
  resources :instructors
  resources :takes
  resources :courses
  resources :st_has_deps
  resources :departments
  resources :students
  resources :studnts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  belongs_to :department
end

app/models/payement.rb
class Payement < ApplicationRecord
  belongs_to :student
end

app/models/st_has_dep.rb
class StHasDep < ApplicationRecord
  belongs_to :department
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/studnt.rb
class Studnt < ApplicationRecord
end

app/models/take.rb
class Take < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/teache.rb
class Teache < ApplicationRecord
  belongs_to :instructor
  belongs_to :course
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:Course_name, :CS_duration)
    end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:Ins_name, :F_name, :Cell, :Email, :department_id)
    end
end

app/controllers/takes_controller.rb
class TakesController < ApplicationController
  before_action :set_take, only: [:show, :edit, :update, :destroy]

  # GET /takes
  # GET /takes.json
  def index
    @takes = Take.all
  end

  # GET /takes/1
  # GET /takes/1.json
  def show
  end

  # GET /takes/new
  def new
    @take = Take.new
  end

  # GET /takes/1/edit
  def edit
  end

  # POST /takes
  # POST /takes.json
  def create
    @take = Take.new(take_params)

    respond_to do |format|
      if @take.save
        format.html { redirect_to @take, notice: 'Take was successfully created.' }
        format.json { render :show, status: :created, location: @take }
      else
        format.html { render :new }
        format.json { render json: @take.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /takes/1
  # PATCH/PUT /takes/1.json
  def update
    respond_to do |format|
      if @take.update(take_params)
        format.html { redirect_to @take, notice: 'Take was successfully updated.' }
        format.json { render :show, status: :ok, location: @take }
      else
        format.html { render :edit }
        format.json { render json: @take.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /takes/1
  # DELETE /takes/1.json
  def destroy
    @take.destroy
    respond_to do |format|
      format.html { redirect_to takes_url, notice: 'Take was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_take
      @take = Take.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def take_params
      params.require(:take).permit(:student_id, :course_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/payements_helper.rb
module PayementsHelper
end

app/helpers/st_has_deps_helper.rb
module StHasDepsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/studnts_helper.rb
module StudntsHelper
end

app/helpers/takes_helper.rb
module TakesHelper
end

app/helpers/teaches_helper.rb
module TeachesHelper
end

app/views/instructors/_form.html.erb
<%= form_for(instructor) do |f| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Ins_name %>
    <%= f.text_field :Ins_name %>
  </div>

  <div class="field">
    <%= f.label :F_name %>
    <%= f.text_field :F_name %>
  </div>

  <div class="field">
    <%= f.label :Cell %>
    <%= f.text_field :Cell %>
  </div>

  <div class="field">
    <%= f.label :Email %>
    <%= f.text_field :Email %>
  </div>

  <div class="field">
    <%= f.label :department_id %>
    <%= f.text_field :department_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instructors</h1>

<table>
  <thead>
    <tr>
      <th>Ins name</th>
      <th>F name</th>
      <th>Cell</th>
      <th>Email</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.Ins_name %></td>
        <td><%= instructor.F_name %></td>
        <td><%= instructor.Cell %></td>
        <td><%= instructor.Email %></td>
        <td><%= instructor.department %></td>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ins name:</strong>
  <%= @instructor.Ins_name %>
</p>

<p>
  <strong>F name:</strong>
  <%= @instructor.F_name %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @instructor.Cell %>
</p>

<p>
  <strong>Email:</strong>
  <%= @instructor.Email %>
</p>

<p>
  <strong>Department:</strong>
  <%= @instructor.department %>
</p>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>