config/routes.rb
Rails.application.routes.draw do
  resources :payements
  resources :teaches
  resources :instructors
  resources :takes
  resources :courses
  resources :st_has_deps
  resources :departments
  resources :students
  resources :studnts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  belongs_to :department
end

app/models/payement.rb
class Payement < ApplicationRecord
  belongs_to :student
end

app/models/st_has_dep.rb
class StHasDep < ApplicationRecord
  belongs_to :department
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/studnt.rb
class Studnt < ApplicationRecord
end

app/models/take.rb
class Take < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/teache.rb
class Teache < ApplicationRecord
  belongs_to :instructor
  belongs_to :course
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:Course_name, :CS_duration)
    end
end

app/controllers/payements_controller.rb
class PayementsController < ApplicationController
  before_action :set_payement, only: [:show, :edit, :update, :destroy]

  # GET /payements
  # GET /payements.json
  def index
    @payements = Payement.all
  end

  # GET /payements/1
  # GET /payements/1.json
  def show
  end

  # GET /payements/new
  def new
    @payement = Payement.new
  end

  # GET /payements/1/edit
  def edit
  end

  # POST /payements
  # POST /payements.json
  def create
    @payement = Payement.new(payement_params)

    respond_to do |format|
      if @payement.save
        format.html { redirect_to @payement, notice: 'Payement was successfully created.' }
        format.json { render :show, status: :created, location: @payement }
      else
        format.html { render :new }
        format.json { render json: @payement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payements/1
  # PATCH/PUT /payements/1.json
  def update
    respond_to do |format|
      if @payement.update(payement_params)
        format.html { redirect_to @payement, notice: 'Payement was successfully updated.' }
        format.json { render :show, status: :ok, location: @payement }
      else
        format.html { render :edit }
        format.json { render json: @payement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payements/1
  # DELETE /payements/1.json
  def destroy
    @payement.destroy
    respond_to do |format|
      format.html { redirect_to payements_url, notice: 'Payement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payement
      @payement = Payement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payement_params
      params.require(:payement).permit(:Ammount, :Discount, :Total_fee, :Remaining_fee, :Pay_date, :student_id)
    end
end

app/controllers/takes_controller.rb
class TakesController < ApplicationController
  before_action :set_take, only: [:show, :edit, :update, :destroy]

  # GET /takes
  # GET /takes.json
  def index
    @takes = Take.all
  end

  # GET /takes/1
  # GET /takes/1.json
  def show
  end

  # GET /takes/new
  def new
    @take = Take.new
  end

  # GET /takes/1/edit
  def edit
  end

  # POST /takes
  # POST /takes.json
  def create
    @take = Take.new(take_params)

    respond_to do |format|
      if @take.save
        format.html { redirect_to @take, notice: 'Take was successfully created.' }
        format.json { render :show, status: :created, location: @take }
      else
        format.html { render :new }
        format.json { render json: @take.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /takes/1
  # PATCH/PUT /takes/1.json
  def update
    respond_to do |format|
      if @take.update(take_params)
        format.html { redirect_to @take, notice: 'Take was successfully updated.' }
        format.json { render :show, status: :ok, location: @take }
      else
        format.html { render :edit }
        format.json { render json: @take.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /takes/1
  # DELETE /takes/1.json
  def destroy
    @take.destroy
    respond_to do |format|
      format.html { redirect_to takes_url, notice: 'Take was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_take
      @take = Take.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def take_params
      params.require(:take).permit(:student_id, :course_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/payements_helper.rb
module PayementsHelper
end

app/helpers/st_has_deps_helper.rb
module StHasDepsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/studnts_helper.rb
module StudntsHelper
end

app/helpers/takes_helper.rb
module TakesHelper
end

app/helpers/teaches_helper.rb
module TeachesHelper
end

app/views/payements/_form.html.erb
<%= form_for(payement) do |f| %>
  <% if payement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payement.errors.count, "error") %> prohibited this payement from being saved:</h2>

      <ul>
      <% payement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Ammount %>
    <%= f.number_field :Ammount %>
  </div>

  <div class="field">
    <%= f.label :Discount %>
    <%= f.text_field :Discount %>
  </div>

  <div class="field">
    <%= f.label :Total_fee %>
    <%= f.number_field :Total_fee %>
  </div>

  <div class="field">
    <%= f.label :Remaining_fee %>
    <%= f.number_field :Remaining_fee %>
  </div>

  <div class="field">
    <%= f.label :Pay_date %>
    <%= f.date_select :Pay_date %>
  </div>

  <div class="field">
    <%= f.label :student_id %>
    <%= f.text_field :student_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payements/edit.html.erb
<h1>Editing Payement</h1>

<%= render 'form', payement: @payement %>

<%= link_to 'Show', @payement %> |
<%= link_to 'Back', payements_path %>

app/views/payements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payements</h1>

<table>
  <thead>
    <tr>
      <th>Ammount</th>
      <th>Discount</th>
      <th>Total fee</th>
      <th>Remaining fee</th>
      <th>Pay date</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payements.each do |payement| %>
      <tr>
        <td><%= payement.Ammount %></td>
        <td><%= payement.Discount %></td>
        <td><%= payement.Total_fee %></td>
        <td><%= payement.Remaining_fee %></td>
        <td><%= payement.Pay_date %></td>
        <td><%= payement.student %></td>
        <td><%= link_to 'Show', payement %></td>
        <td><%= link_to 'Edit', edit_payement_path(payement) %></td>
        <td><%= link_to 'Destroy', payement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payement', new_payement_path %>

app/views/payements/new.html.erb
<h1>New Payement</h1>

<%= render 'form', payement: @payement %>

<%= link_to 'Back', payements_path %>

app/views/payements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ammount:</strong>
  <%= @payement.Ammount %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @payement.Discount %>
</p>

<p>
  <strong>Total fee:</strong>
  <%= @payement.Total_fee %>
</p>

<p>
  <strong>Remaining fee:</strong>
  <%= @payement.Remaining_fee %>
</p>

<p>
  <strong>Pay date:</strong>
  <%= @payement.Pay_date %>
</p>

<p>
  <strong>Student:</strong>
  <%= @payement.student %>
</p>

<%= link_to 'Edit', edit_payement_path(@payement) %> |
<%= link_to 'Back', payements_path %>