config/routes.rb
Rails.application.routes.draw do
  resources :payements
  resources :teaches
  resources :instructors
  resources :takes
  resources :courses
  resources :st_has_deps
  resources :departments
  resources :students
  resources :studnts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  belongs_to :department
end

app/models/payement.rb
class Payement < ApplicationRecord
  belongs_to :student
end

app/models/st_has_dep.rb
class StHasDep < ApplicationRecord
  belongs_to :department
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/studnt.rb
class Studnt < ApplicationRecord
end

app/models/take.rb
class Take < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/teache.rb
class Teache < ApplicationRecord
  belongs_to :instructor
  belongs_to :course
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:Course_name, :CS_duration)
    end
end

app/controllers/studnts_controller.rb
class StudntsController < ApplicationController
  before_action :set_studnt, only: [:show, :edit, :update, :destroy]

  # GET /studnts
  # GET /studnts.json
  def index
    @studnts = Studnt.all
  end

  # GET /studnts/1
  # GET /studnts/1.json
  def show
  end

  # GET /studnts/new
  def new
    @studnt = Studnt.new
  end

  # GET /studnts/1/edit
  def edit
  end

  # POST /studnts
  # POST /studnts.json
  def create
    @studnt = Studnt.new(studnt_params)

    respond_to do |format|
      if @studnt.save
        format.html { redirect_to @studnt, notice: 'Studnt was successfully created.' }
        format.json { render :show, status: :created, location: @studnt }
      else
        format.html { render :new }
        format.json { render json: @studnt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studnts/1
  # PATCH/PUT /studnts/1.json
  def update
    respond_to do |format|
      if @studnt.update(studnt_params)
        format.html { redirect_to @studnt, notice: 'Studnt was successfully updated.' }
        format.json { render :show, status: :ok, location: @studnt }
      else
        format.html { render :edit }
        format.json { render json: @studnt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studnts/1
  # DELETE /studnts/1.json
  def destroy
    @studnt.destroy
    respond_to do |format|
      format.html { redirect_to studnts_url, notice: 'Studnt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studnt
      @studnt = Studnt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def studnt_params
      params.require(:studnt).permit(:St_name, :F_name, :Gender, :Address, :Cell#, :Local, :CNIC)
    end
end

app/controllers/takes_controller.rb
class TakesController < ApplicationController
  before_action :set_take, only: [:show, :edit, :update, :destroy]

  # GET /takes
  # GET /takes.json
  def index
    @takes = Take.all
  end

  # GET /takes/1
  # GET /takes/1.json
  def show
  end

  # GET /takes/new
  def new
    @take = Take.new
  end

  # GET /takes/1/edit
  def edit
  end

  # POST /takes
  # POST /takes.json
  def create
    @take = Take.new(take_params)

    respond_to do |format|
      if @take.save
        format.html { redirect_to @take, notice: 'Take was successfully created.' }
        format.json { render :show, status: :created, location: @take }
      else
        format.html { render :new }
        format.json { render json: @take.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /takes/1
  # PATCH/PUT /takes/1.json
  def update
    respond_to do |format|
      if @take.update(take_params)
        format.html { redirect_to @take, notice: 'Take was successfully updated.' }
        format.json { render :show, status: :ok, location: @take }
      else
        format.html { render :edit }
        format.json { render json: @take.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /takes/1
  # DELETE /takes/1.json
  def destroy
    @take.destroy
    respond_to do |format|
      format.html { redirect_to takes_url, notice: 'Take was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_take
      @take = Take.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def take_params
      params.require(:take).permit(:student_id, :course_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/payements_helper.rb
module PayementsHelper
end

app/helpers/st_has_deps_helper.rb
module StHasDepsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/studnts_helper.rb
module StudntsHelper
end

app/helpers/takes_helper.rb
module TakesHelper
end

app/helpers/teaches_helper.rb
module TeachesHelper
end

app/views/studnts/_form.html.erb
<%= form_for(studnt) do |f| %>
  <% if studnt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(studnt.errors.count, "error") %> prohibited this studnt from being saved:</h2>

      <ul>
      <% studnt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :St_name %>
    <%= f.text_field :St_name %>
  </div>

  <div class="field">
    <%= f.label :F_name %>
    <%= f.text_field :F_name %>
  </div>

  <div class="field">
    <%= f.label :Gender %>
    <%= f.text_field :Gender %>
  </div>

  <div class="field">
    <%= f.label :Address %>
    <%= f.text_area :Address %>
  </div>

  <div class="field">
    <%= f.label :Cell# %>
    <%= f.text_field :Cell# %>
  </div>

  <div class="field">
    <%= f.label :Local %>
    <%= f.text_field :Local %>
  </div>

  <div class="field">
    <%= f.label :CNIC %>
    <%= f.text_field :CNIC %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/studnts/edit.html.erb
<h1>Editing Studnt</h1>

<%= render 'form', studnt: @studnt %>

<%= link_to 'Show', @studnt %> |
<%= link_to 'Back', studnts_path %>

app/views/studnts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Studnts</h1>

<table>
  <thead>
    <tr>
      <th>St name</th>
      <th>F name</th>
      <th>Gender</th>
      <th>Address</th>
      <th>Cell#</th>
      <th>Local</th>
      <th>Cnic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @studnts.each do |studnt| %>
      <tr>
        <td><%= studnt.St_name %></td>
        <td><%= studnt.F_name %></td>
        <td><%= studnt.Gender %></td>
        <td><%= studnt.Address %></td>
        <td><%= studnt.Cell# %></td>
        <td><%= studnt.Local %></td>
        <td><%= studnt.CNIC %></td>
        <td><%= link_to 'Show', studnt %></td>
        <td><%= link_to 'Edit', edit_studnt_path(studnt) %></td>
        <td><%= link_to 'Destroy', studnt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Studnt', new_studnt_path %>

app/views/studnts/new.html.erb
<h1>New Studnt</h1>

<%= render 'form', studnt: @studnt %>

<%= link_to 'Back', studnts_path %>

app/views/studnts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>St name:</strong>
  <%= @studnt.St_name %>
</p>

<p>
  <strong>F name:</strong>
  <%= @studnt.F_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @studnt.Gender %>
</p>

<p>
  <strong>Address:</strong>
  <%= @studnt.Address %>
</p>

<p>
  <strong>Cell#:</strong>
  <%= @studnt.Cell# %>
</p>

<p>
  <strong>Local:</strong>
  <%= @studnt.Local %>
</p>

<p>
  <strong>Cnic:</strong>
  <%= @studnt.CNIC %>
</p>

<%= link_to 'Edit', edit_studnt_path(@studnt) %> |
<%= link_to 'Back', studnts_path %>

app/views/takes/_form.html.erb
<%= form_for(take) do |f| %>
  <% if take.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(take.errors.count, "error") %> prohibited this take from being saved:</h2>

      <ul>
      <% take.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %>
    <%= f.text_field :student_id %>
  </div>

  <div class="field">
    <%= f.label :course_id %>
    <%= f.text_field :course_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/takes/edit.html.erb
<h1>Editing Take</h1>

<%= render 'form', take: @take %>

<%= link_to 'Show', @take %> |
<%= link_to 'Back', takes_path %>

app/views/takes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Takes</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @takes.each do |take| %>
      <tr>
        <td><%= take.student %></td>
        <td><%= take.course %></td>
        <td><%= link_to 'Show', take %></td>
        <td><%= link_to 'Edit', edit_take_path(take) %></td>
        <td><%= link_to 'Destroy', take, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Take', new_take_path %>

app/views/takes/new.html.erb
<h1>New Take</h1>

<%= render 'form', take: @take %>

<%= link_to 'Back', takes_path %>

app/views/takes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @take.student %>
</p>

<p>
  <strong>Course:</strong>
  <%= @take.course %>
</p>

<%= link_to 'Edit', edit_take_path(@take) %> |
<%= link_to 'Back', takes_path %>